api = "0.2"

[buildpack]
id = "datadog/heroku"
version = "0.0.1"
name = "Datadog Heroku Buildpack"
homepage = "https://github.com/DataDog/heroku-buildpack-datadog"

[[stacks]]
id = "heroku-18"

[[stacks]]
id = "heroku-20"
